# Generated by Django 3.2.8 on 2021-11-29 13:23

from django.db import migrations, models
import django.db.models.deletion


def populate_names(apps, schema_editor):
    names = ["12 Reasons this project is not impressive", "3 Valid reason this project is not impressive", "The actual reason this project is not impressive"]                               
    Author = apps.get_model('inventory', 'Author')
    obj = Author(full_name="Kaido w'Anas w'Rihab", dob="1999-08-29")
    obj.save()
    
    Book = apps.get_model('inventory', 'Book')
    for name in names:
        obj = Book(title=name, author_field_id=1)
        obj.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('allmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.allmodels')),
                ('full_name', models.CharField(max_length=500)),
                ('dob', models.DateField()),
            ],
            bases=('inventory.allmodels',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('allmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.allmodels')),
                ('title', models.CharField(max_length=500)),
                ('author_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.author')),
            ],
            bases=('inventory.allmodels',),
        ),
        migrations.RunPython(populate_names)
    ]
